name: "Test"
on:
  push:
  schedule:
    - cron: '5 19 * * 5'  # At 19:05 on Friday
jobs:
  nixos-22-11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-22.11
    - run: nix-build
    - run: nix-shell --command 'pytest -v tests/ acceptance_tests'
    - run: |
        nix-env -if default.nix && nix-shell -p bats --command './acceptance_tests/test_command.sh'
  nixos-unstable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build --arg runMypy false  # TODO run mypy in unstable
    - run: nix-shell --command 'pytest -v tests/ acceptance_tests'
    - run: |
        nix-env -if default.nix --arg runMypy false && nix-shell -p bats --command './acceptance_tests/test_command.sh'  # TODO run mypy in unstable
